//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BreakableTile.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//

/**
 * A torekeny csempe viselkedeset megvalosito osztaly.
 * @author Konczos
 */


public class BreakableTile extends Tile {
    /**
     * A csempe elettartamat tarolo int.
     */
    private int health;
    /**
     * A csempe allapotat(torott/ep) jelzo boolean.
     */
    private boolean broken;

    /**
     * Getter fuggveny a health valtozohoz.
     * @return A health valtozo, azaz a csempe elete.
     */
    public int getHealth() {
        System.out.println(">   getHealth()");
        System.out.println("<   getHealth()");
        return health;
    }

    /**
     * Getter fuggveny a broken valtozohoz.
     * @return A broken valtozo, azaz, hogy torott e a csempe.
     */
    public boolean isBroken() {
        System.out.println(">   isBroken()");
        System.out.println("<   isBroken()");
        return broken;
    }

    /**
     * Setter fuggveny a health valtozohoz.
     * @param newHealth Az health valtozo uj erteke.
     */
    public void setHealth(int newHealth){
        System.out.println(">   setHealth(int newHealth)");
        health = newHealth;
        System.out.println("<   setHealth(int newHealth)");

    }

    /**
     * Setter fuggveny a broken valtozohoz.
     * @param newBroken A broken valtozo uj erteke.
     */
    public void  setBroken(boolean newBroken){
        System.out.println(">   setBroken(boolean newBroken)");
        broken = newBroken;
        System.out.println("<   setBroken(boolean newBroken)");

    }

    /**
     * A fuggveny egyel csökkenti a törékeny csempe elettartamat.
     */
    public void decreaseHealth() {
        System.out.println(">   decreaseHealth()");

        health--;
        if(health == 0){
            broken = true;
            localAnimal.die();
        }
        System.out.println("<   decreaseHealth()");

    }

    /**
     * Amennyiben az allat a csempere akar lepni, ez a fuggveny hivodik meg.
     *
     * @param a Az allat, amely a csempere akar lepni.
     */
    public void receive (Animal a){
        System.out.println(">   receive (Animal a)");

        if(broken) {
            a.die();
        }
        else{
            localAnimal = a;
            decreaseHealth();
        }
        System.out.println("<   receive (Animal a)");

    }
}
