//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BreakableTile.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//

/**
 * A torekeny csempe viselkedeset megvalosito osztaly
 * @author Konczos
 */


public class BreakableTile extends Tile {
    /**
     * A csempe élettartamat tarolo int
     */
    public int health;
    /**
     * A csempe allapotat(torott/ep) jelzo boolean.
     */
    public boolean broken;

    /**
     * A fuggveny egyel csökkenti a törékeny csempe elettartamat
     */
    public void decreaseHealth() {
        health--;
    }
}
