//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ChocoAutomat.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public class ChocoAutomat extends Item {

    private Tile onTile;

    @Override
    public void countDown() {
        --Counter;
        if(Counter <= 0) {
//            Tile[] Neighbours = onTile.getNeighbours();
//            for(int i = 0; i < Neighbours.size(); ++i) {
//                Neighbours[i].beep();
//            }
            Counter = 100;
        }
    }

    public ChocoAutomat(Tile t){
        onTile = t;
        Counter = 100;
    }
    
    public void delegateTick();
    
    public void doYourThing();
}
