//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Couch.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//


/**
 * A kanapet megvalosito osztaly.
 *
 * @author Cynolter
 */
public class Couch extends Item {

    /**
     * A kanapen eppen ulo pandat reprezentalo attributum.
     */
    private Panda RestingPanda;

    /**
     * A countDown metodus segítségével tudjak majd a szomszedos mezon allok, hogy itt kanape van.
     */
    @Override
    public void countDown() {
        GameLogic.indent(true);
        System.out.println(">   Couch::countDown()");
        onTile.tire(onTile);
        GameLogic.indent(false);
        System.out.println("<   Couch::countDown()");
    }

    /**
     * Ha egy panda le akar ulni, a kanape megnezi, hogy ures-e (azaz le tud-e ulni a panda), ha ures, akkor leulteti.
     *
     * @param p A panda amelyet leultetunk a kanapera.
     */
    @Override
    public void receive(Panda p) {
        GameLogic.indent(true);
        System.out.println(">   Couch::receive(Panda p)");
        if (RestingPanda == null) {
            RestingPanda = p;
        }
        GameLogic.indent(false);
        System.out.println("<   Couch::receive(Panda p)");
    }

    /**
     * A konstruktor, amelyben beallitjuk, hogy alapbol nincs panda a kanapen.
     *
     * @param t A csempe, amelyiken a kanape talalhato.
     */
    public Couch(Tile t) {
        GameLogic.indent(true);
        System.out.println(">   Couch::Couch(Tile t)");
        onTile = t;
        RestingPanda = null;
        GameLogic.indent(false);
        System.out.println("<   Couch::Couch(Tile t)");
    }
}
