//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : EntryWardrobe.java
//  @ Date : 2019.03.23.
//  @ Author : Kalai
//
//

/**
 * Osztaly a bemeneti szekrenyek viselkedesenek es tulajdonsagaiknak osszegyujtesere,
 * az ExitPoint osztaly ebbol az osztalybol szarmazik.
 * @author Kalai
 * @see BaseTile
 */
public class EntryWardrobe extends BaseTile {
    /**
     * Referencia a kimeneti szekrenyre, vagyis egy specialis csempere.
     */
    protected Tile destination;

    /**
     * Setter fuggveny a destination valtozo megvaltoztatasara.
     *
     * @param t A kimeneti szekreny.
     */
    public void setDestination(Tile t){
        destination = t;
        return;
    }

    /**
     * Getter fuggveny a destination valtozo lekerdezesere.
     *
     * @return A kimeneti szekreny.
     */
    public BaseTile getDestination() {
        return destination;
    }
}
