//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EntryWardrobe.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public class EntryWardrobe extends BaseTile {
    public BaseTile getDestination() {
    }
}
