//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ExitWardrobe.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public class ExitWardrobe extends BaseTile {
}
