//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Projlab
//  @ File Name : ExitPoint.java
//  @ Date : 2019.03.23
//  @ Author : Kalai
//
//

/**
 * Osztaly a kijarat viselkedesenek es tulajdonsagaiknak osszegyujtesere.
 * @author Kalai
 * @see EntryWardrobe
 */
public class ExitPoint extends EntryWardrobe {

    /**
     * A kijarati pont egy referencian kereszul eri el a GameLogicot.
     */
    private GameLogic gameLogic;

    /**
     * Csempe amelyre az orangutan visszater, miutan kivezette a pandakat
     * a kijaraton keresztul.
     */
    private Tile startingTile ;

    /**
     * Beallitja a kezdo csempet.
     * @param sT a kezdo csempere vonatkozo referencia.
     */
    void setStartingTile(Tile sT){
        System.out.println(">   setStartingTile(Tile sT)");
        startingTile = sT;
        System.out.println("<   setStartingTile(Tile sT)");
		return;
    }

    /**
     * Az ide lepo allatot a bejaratra teszi, levalasztja a pandakat, es
     * pontot oszt ertuk.
     *
     * @param a Az allat (orangutan) amely a kijaratra lepett.
     */
    public void receive(Animal a) {
        System.out.println(">   receive(Animal a)");
        localAnimal.setTile(startingTile);
        int i = 0;
        for (Panda p: localAnimal.getCaughtPandas()) {
            gameLogic.remove(p);
            ++i;
        }
        gameLogic.addPoints(i);
        System.out.println("<   receive(Animal a)");
        return;
    }
}
