//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GameLogic.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public class GameLogic implements ITimeable {
    public void game() {
    }
    
    public void addPoints() {
    }
    
    public void endGame() {
    }
    
    public void tick() {
    }
    
    public void delegateTick();
}
