//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : InteractiveThings.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public interface InteractiveThings {
    public void doYourThing();
}
