//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public abstract class Item implements ITimeable, InteractiveThings {

    protected int Counter;

    public Item() {

    }

    public void countDown() {
    }
    
    public void delegateTick();
    
    public void doYourThing();
}
