//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//


/**
 * A poliformizmust tamogato ososztaly a jatekban megtalalhato targyakhoz.
 *
 * @author Cynolter
 */
public abstract class Item {
    /**
     * Nev, amivel a teszteles soran azonositani lehet az objektumot.
     */
    private String name;

    /**
     * A szamlalo, amely ha lejar akkor a csokiautomata sipolhat és a jatekgep csoroghet.
     */
    protected int Counter;
    /**
     * A csempe, amelyiken a targy all.
     */
    protected Tile onTile;

    /**
     * Leszarmazott specifikus, hogy mit kell csinalnia countDown-ra, a leszarmazottaknal van implementalva.
     */
    public void countDown() {
    }

    public void receive(TiredPanda p) {
    }

    public void standUp() {
    }

    public abstract void doAction();

    public String getName() {
        return name;
    }

    public void setName(String n) {
        name = n;
    }

    /**
     * Az item tipusanak lekerdezese.
     *
     * @return Az item tipusa.
     */
    public String getType() {
        return "";
    }
}
