//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ITimeable.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public interface ITimeable {
    public void delegateTick();
}
