//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : JumpingPanda.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public class JumpingPanda extends Panda {
    public void jump() {
    }
    
    public void delegateTick();
    
    public void doYourThing();
}
