//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Orangutan.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public class Orangutan extends Animal implements IAnimal {
    public void collision(Animal a) {
    }
    
    public void release(Panda p) {
    }
    
    public void die() {
    }
    
    public void delegateTick();
}
