//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ScarablePanda.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public class ScarablePanda extends Panda {
    public void scare() {
    }
    
    public void delegateTick();
    
    public void doYourThing();
}
