//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tile.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public class Tile extends BaseTile implements ITimeable {
    public void beep() {
    }
    
    public void ring() {
    }
    
    public void tire(Tile t) {
    }
    
    public void setItem(Item i) {
    }
    
    public void setAnimal(Animal a) {
    }
    
    public void delegateTick();
}
