//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TiredPanda.java
//  @ Date : 2019.03.20.
//  @ Author : 
//
//




public class TiredPanda extends Panda {
    public void sit(Tile t) {
    }
    
    public void delegateTick();
    
    public void doYourThing();
}
